package Position;

import Attributes.StatAttributes;

import java.util.Arrays;
import java.util.List;

public enum BaseAttributes {

//    General mean configuration.
    /**
     * Take mean for overall, divide by 80, multiply by the positions MEAN_OVERALL, and that is your
     * mean for the attribute.
     * EG
     *
     * If we wanted the mean for QB_AWARENESS to be a 80, we would do as follows.
     *
     * (mean/80) * positionMeanOverall =
     *
     * (80/80) * .72 = .72
     *
     * As you see below, we get .72 for the mean rating (out of 1) of awareness for QB.
     *
     */

    /**
     * DO NOT ADJUST THESE FOR SUB POSITION RELATED THINGS.
     * DO THOSE ADJUSTMENTS IN THE RELEVANT SUB POSITION FILE.
     *
     * ADJUSTING THESE WILL AFFECT ALL SUB POSITIONS OF THE RELEVANT POSITION
     */

    QB_AWARENESS(StatAttributes.AWARENESS.getName(), 0.72, .045, 0.093),
    QB_STRENGTH(StatAttributes.STRENGTH.getName(), 0.625, .04, 0.08),
    QB_SPEED(StatAttributes.SPEED.getName(), .6, .05, 0.16),
    QB_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.19, .03, 0.03),
    QB_TACKLE(StatAttributes.TACKLE.getName(), 0.39, .03, 0.06),
    QB_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), 0.25, .03, 0.04),
    QB_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), 0.25, .03, 0.04),
    QB_CATCHING(StatAttributes.CATCHING.getName(), 0.45, .12, 0.20),
    QB_CARRYING(StatAttributes.CARRYING.getName(), 0.567, .04, 0.05),
    QB_ACCELERATION(StatAttributes.ACCELERATION.getName(), .72, .03, 0.17),
    QB_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.63, .04, 0.05),
    QB_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), 0.65, .05, 0.11),
    QB_AGILITY(StatAttributes.AGILITY.getName(), .72, .05, 0.10),
    QB_INJURY(StatAttributes.INJURY.getName(), .77, .03, 0.04),
    QB_STAMINA(StatAttributes.STAMINA.getName(), .824, .03, 0.04),
    QB_THROW_POWER(StatAttributes.THROW_POWER.getName(), .79, .025, 0.7),
    QB_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), 0.18, .03, 0.03),
    QB_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), 0.26, .03, 0.04),
    QB_KICK_POWER(StatAttributes.KICK_POWER.getName(), 0.31, .03, 0.05),
    QB_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), 0.28, .03, 0.04),
    QB_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), .711, .015, 0.05),
    QB_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), 0.24, .03, 0.04),

    TE_AWARENESS(StatAttributes.AWARENESS.getName(), 0.65, .03, 0.07),
    TE_STRENGTH(StatAttributes.STRENGTH.getName(), 0.67, .03, 0.07),
    TE_SPEED(StatAttributes.SPEED.getName(), .65, .035, 0.10),
    TE_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.38, .03, 0.06),
    TE_TACKLE(StatAttributes.TACKLE.getName(), 0.40, .03, 0.12),
    TE_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), .667, .03, 0.10),
    TE_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), .667, .03, 0.10),
    TE_CATCHING(StatAttributes.CATCHING.getName(), .667, .03, 0.10),
    TE_CARRYING(StatAttributes.CARRYING.getName(), .667, .03, 0.10),
    TE_ACCELERATION(StatAttributes.ACCELERATION.getName(), .650, .03, 0.07),
    TE_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.418, .04, 0.15),
    TE_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), 0.388, .04, 0.12),
    TE_AGILITY(StatAttributes.AGILITY.getName(), .651, .03, 0.07),
    TE_INJURY(StatAttributes.INJURY.getName(), .77, .03, 0.10),
    TE_STAMINA(StatAttributes.STAMINA.getName(), .80, .03, 0.10),
    TE_THROW_POWER(StatAttributes.THROW_POWER.getName(), 0.46, .03, 0.07),
    TE_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), 0.23, .03, 0.03),
    TE_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), 0.32, .03, 0.05),
    TE_KICK_POWER(StatAttributes.KICK_POWER.getName(), 0.3, .03, 0.04),
    TE_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), 0.28, .03, 0.04),
    TE_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), 0.2, .03, 0.03),
    TE_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), 0.65, .03, 0.10),

    WR_AWARENESS(StatAttributes.AWARENESS.getName(), 0.721, .03, 0.07),
    WR_STRENGTH(StatAttributes.STRENGTH.getName(), 0.54, .035, 0.12),
    WR_SPEED(StatAttributes.SPEED.getName(), .826, .025, 0.05),
    WR_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.26, .03, 0.04),
    WR_TACKLE(StatAttributes.TACKLE.getName(), 0.35, .045, 0.12),
    WR_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), 0.421, .03, 0.07),
    WR_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), 0.421, .03, 0.07),
    WR_CATCHING(StatAttributes.CATCHING.getName(), .810, .03, 0.05),
    WR_CARRYING(StatAttributes.CARRYING.getName(), 0.684, .03, 0.07),
    WR_ACCELERATION(StatAttributes.ACCELERATION.getName(), .851, .0175, 0.07),
    WR_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.60, .03, 0.07),
    WR_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), .703, .03, 0.07),
    WR_AGILITY(StatAttributes.AGILITY.getName(), .823, .03, 0.06),
    WR_INJURY(StatAttributes.INJURY.getName(), .78, .03, 0.10),
    WR_STAMINA(StatAttributes.STAMINA.getName(), .81, .03, 0.10),
    WR_THROW_POWER(StatAttributes.THROW_POWER.getName(), 0.48, .03, 0.07),
    WR_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), 0.25, .03, 0.04),
    WR_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), 0.34, .03, 0.05),
    WR_KICK_POWER(StatAttributes.KICK_POWER.getName(), 0.3, .03, 0.04),
    WR_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), 0.27, .03, 0.04),
    WR_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), 0.26, .03, 0.04),
    WR_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), .75, .025, 0.07),

    OLB_AWARENESS(StatAttributes.AWARENESS.getName(), 0.68, .03, 0.10),
    OLB_STRENGTH(StatAttributes.STRENGTH.getName(), .698, .03, 0.07),
    OLB_SPEED(StatAttributes.SPEED.getName(), .734, .03, 0.07),
    OLB_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.685, .03, 0.10),
    OLB_TACKLE(StatAttributes.TACKLE.getName(), .747, .03, 0.07),
    OLB_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), 0.38, .03, 0.15),
    OLB_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), 0.38, .03, 0.15),
    OLB_CATCHING(StatAttributes.CATCHING.getName(), 0.482, .03, 0.12),
    OLB_CARRYING(StatAttributes.CARRYING.getName(), 0.49, .03, 0.11),
    OLB_ACCELERATION(StatAttributes.ACCELERATION.getName(), .775, .02, 0.04),
    OLB_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.39, .03, 0.06),
    OLB_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), 0.51, .03, 0.08),
    OLB_AGILITY(StatAttributes.AGILITY.getName(), .72, .03, 0.07),
    OLB_INJURY(StatAttributes.INJURY.getName(), .772, .03, 0.07),
    OLB_STAMINA(StatAttributes.STAMINA.getName(), .785, .03, 0.07),
    OLB_THROW_POWER(StatAttributes.THROW_POWER.getName(), 0.35, .03, 0.05),
    OLB_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), 0.509, .03, 0.07),
    OLB_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), 0.56, .03, 0.07),
    OLB_KICK_POWER(StatAttributes.KICK_POWER.getName(), 0.29, .03, 0.04),
    OLB_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), 0.26, .03, 0.04),
    OLB_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), 0.11, .03, 0.02),
    OLB_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), 0.19, .03, 0.03),

    MLB_AWARENESS(StatAttributes.AWARENESS.getName(), 0.763, .02, 0.05),
    MLB_STRENGTH(StatAttributes.STRENGTH.getName(), .66, .03, 0.07),
    MLB_SPEED(StatAttributes.SPEED.getName(), .746, .03, 0.07),
    MLB_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.683, .03, 0.07),
    MLB_TACKLE(StatAttributes.TACKLE.getName(), .763, .02, 0.05),
    MLB_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), 0.399, .03, 0.15),
    MLB_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), 0.399, .03, 0.15),
    MLB_CATCHING(StatAttributes.CATCHING.getName(), 0.541, .03, 0.09),
    MLB_CARRYING(StatAttributes.CARRYING.getName(), 0.470, .03, 0.11),
    MLB_ACCELERATION(StatAttributes.ACCELERATION.getName(), .781, .01, 0.03),
    MLB_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.28, .03, 0.06),
    MLB_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), 0.30, .03, 0.08),
    MLB_AGILITY(StatAttributes.AGILITY.getName(), .723, .03, 0.07),
    MLB_INJURY(StatAttributes.INJURY.getName(), .772, .03, 0.07),
    MLB_STAMINA(StatAttributes.STAMINA.getName(), .79, .03, 0.07),
    MLB_THROW_POWER(StatAttributes.THROW_POWER.getName(), 0.34, .03, 0.05),
    MLB_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), 0.621, .03, 0.07),
    MLB_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), 0.693, .03, 0.07),
    MLB_KICK_POWER(StatAttributes.KICK_POWER.getName(), 0.27, .03, 0.04),
    MLB_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), 0.25, .03, 0.04),
    MLB_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), 0.11, .03, 0.02),
    MLB_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), 0.18, .03, 0.03),

    DE_AWARENESS(StatAttributes.AWARENESS.getName(), 0.75, .03, 0.07),
    DE_STRENGTH(StatAttributes.STRENGTH.getName(), .769, .035, 0.07),
    DE_SPEED(StatAttributes.SPEED.getName(), .7219, .03, 0.07),
    DE_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.7219, .035, 0.10),
    DE_TACKLE(StatAttributes.TACKLE.getName(), .7594, .015, 0.03),
    DE_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), 0.48, .03, 0.09),
    DE_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), 0.48, .03, 0.11),
    DE_CATCHING(StatAttributes.CATCHING.getName(), 0.37, .03, 0.06),
    DE_CARRYING(StatAttributes.CARRYING.getName(), 0.47, .0225, 0.05),
    DE_ACCELERATION(StatAttributes.ACCELERATION.getName(), .7828, .0125, 0.04),
    DE_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.33, .03, 0.05),
    DE_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), 0.37, .03, 0.06),
    DE_AGILITY(StatAttributes.AGILITY.getName(), 0.6609, .0275, 0.06),
    DE_INJURY(StatAttributes.INJURY.getName(), .8016, .03, 0.10),
    DE_STAMINA(StatAttributes.STAMINA.getName(), .7547, .03, 0.10),
    DE_THROW_POWER(StatAttributes.THROW_POWER.getName(), 0.31, .03, 0.05),
    DE_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), 0.37, .03, 0.06),
    DE_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), 0.45, .03, 0.08),
    DE_KICK_POWER(StatAttributes.KICK_POWER.getName(), 0.28, .03, 0.04),
    DE_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), 0.25, .03, 0.04),
    DE_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), 0.09, .03, 0.01),
    DE_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), 0.16, .03, 0.02),

    CB_AWARENESS(StatAttributes.AWARENESS.getName(), 0.684, .0475, 0.10),
    CB_STRENGTH(StatAttributes.STRENGTH.getName(), 0.57, .0475, 0.10),
    CB_SPEED(StatAttributes.SPEED.getName(), .8213, .03, 0.07),
    CB_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.452, .0525, 0.15),
    CB_TACKLE(StatAttributes.TACKLE.getName(), 0.575, .03, 0.09),
    CB_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), 0.45, .03, 0.07),
    CB_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), 0.51, .03, 0.08),
    CB_CATCHING(StatAttributes.CATCHING.getName(), 0.575, .03, 0.09),
    CB_CARRYING(StatAttributes.CARRYING.getName(), 0.502, .03, 0.10),
    CB_ACCELERATION(StatAttributes.ACCELERATION.getName(), .821, .0325, 0.08),
    CB_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.502, .04, 0.10),
    CB_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), 0.570, .04, 0.10),
    CB_AGILITY(StatAttributes.AGILITY.getName(), .821, .025, 0.05),
    CB_INJURY(StatAttributes.INJURY.getName(), .784, .03, 0.10),
    CB_STAMINA(StatAttributes.STAMINA.getName(), .826, .035, 0.10),
    CB_THROW_POWER(StatAttributes.THROW_POWER.getName(), 0.38, .03, 0.06),
    CB_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), .739, .03, 0.10),
    CB_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), .694, .03, 0.09),
    CB_KICK_POWER(StatAttributes.KICK_POWER.getName(), 0.26, .03, 0.04),
    CB_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), 0.23, .03, 0.03),
    CB_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), 0.12, .03, 0.02),
    CB_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), 0.3, .03, 0.04),

    OT_AWARENESS(StatAttributes.AWARENESS.getName(), 0.70, .04, 0.12),
    OT_STRENGTH(StatAttributes.STRENGTH.getName(), 0.7394, .03, 0.07),
    OT_SPEED(StatAttributes.SPEED.getName(), 0.573, .03, 0.10),
    OT_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.31, .03, 0.12),
    OT_TACKLE(StatAttributes.TACKLE.getName(), 0.45, .03, 0.12),
    OT_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), .6913, .03, 0.07),
    OT_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), .67, .03, 0.07),
    OT_CATCHING(StatAttributes.CATCHING.getName(), 0.34, .03, 0.05),
    OT_CARRYING(StatAttributes.CARRYING.getName(), 0.53, .03, 0.08),
    OT_ACCELERATION(StatAttributes.ACCELERATION.getName(), .6606, .03, 0.10),
    OT_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.24, .03, 0.04),
    OT_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), 0.21, .03, 0.03),
    OT_AGILITY(StatAttributes.AGILITY.getName(), 0.543, .03, 0.10),
    OT_INJURY(StatAttributes.INJURY.getName(), .77, .03, 0.10),
    OT_STAMINA(StatAttributes.STAMINA.getName(), .80, .03, 0.10),
    OT_THROW_POWER(StatAttributes.THROW_POWER.getName(), 0.33, .03, 0.05),
    OT_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), 0.19, .03, 0.03),
    OT_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), 0.2, .03, 0.03),
    OT_KICK_POWER(StatAttributes.KICK_POWER.getName(), 0.29, .03, 0.04),
    OT_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), 0.26, .03, 0.04),
    OT_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), 0.1, .03, 0.01),
    OT_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), 0.19, .03, 0.03),

    FS_AWARENESS(StatAttributes.AWARENESS.getName(), 0.749, .03, 0.11),
    FS_STRENGTH(StatAttributes.STRENGTH.getName(), 0.60, .03, 0.10),
    FS_SPEED(StatAttributes.SPEED.getName(), .814, .025, 0.05),
    FS_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.4625, .1, 0.25),
    FS_TACKLE(StatAttributes.TACKLE.getName(), 0.6244, .03, 0.08),
    FS_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), 0.40, .03, 0.10),
    FS_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), 0.40, .03, 0.10),
    FS_CATCHING(StatAttributes.CATCHING.getName(), 0.6475, .03, 0.07),
    FS_CARRYING(StatAttributes.CARRYING.getName(), 0.629, .03, 0.10),
    FS_ACCELERATION(StatAttributes.ACCELERATION.getName(), .8325, .03, 0.07),
    FS_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.49, .03, 0.07),
    FS_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), 0.60, .03, 0.10),
    FS_AGILITY(StatAttributes.AGILITY.getName(), .7863, .03, 0.05),
    FS_INJURY(StatAttributes.INJURY.getName(), .78, .03, 0.10),
    FS_STAMINA(StatAttributes.STAMINA.getName(), .82, .03, 0.10),
    FS_THROW_POWER(StatAttributes.THROW_POWER.getName(), 0.36, .03, 0.05),
    FS_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), 0.721, .03, 0.05),
    FS_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), 0.7493, .03, 0.05),
    FS_KICK_POWER(StatAttributes.KICK_POWER.getName(), 0.28, .03, 0.04),
    FS_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), 0.26, .03, 0.04),
    FS_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), 0.15, .03, 0.02),
    FS_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), 0.24, .03, 0.04),

    HB_AWARENESS(StatAttributes.AWARENESS.getName(), 0.722, .03, 0.10),
    HB_STRENGTH(StatAttributes.STRENGTH.getName(), 0.629, .03, 0.10),
    HB_SPEED(StatAttributes.SPEED.getName(), .749, .025, 0.07),
    HB_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.35, .03, 0.12),
    HB_TACKLE(StatAttributes.TACKLE.getName(), 0.46, .03, 0.07),
    HB_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), 0.45, .035, 0.12),
    HB_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), 0.48, .035, 0.12),
    HB_CATCHING(StatAttributes.CATCHING.getName(), 0.65, .04, 0.10),
    HB_CARRYING(StatAttributes.CARRYING.getName(), .763, .03, 0.17),
    HB_ACCELERATION(StatAttributes.ACCELERATION.getName(), .80, .02, 0.05),
    HB_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.698, .03, 0.07),
    HB_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), .680, .03, 0.07),
    HB_AGILITY(StatAttributes.AGILITY.getName(), .749, .03, 0.07),
    HB_INJURY(StatAttributes.INJURY.getName(), .77, .03, 0.07),
    HB_STAMINA(StatAttributes.STAMINA.getName(), .78, .03, 0.07),
    HB_THROW_POWER(StatAttributes.THROW_POWER.getName(), 0.42, .03, 0.06),
    HB_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), 0.2, .03, 0.03),
    HB_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), 0.27, .03, 0.04),
    HB_KICK_POWER(StatAttributes.KICK_POWER.getName(), 0.27, .03, 0.04),
    HB_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), 0.24, .03, 0.04),
    HB_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), 0.27, .03, 0.04),
    HB_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), 0.55, .03, 0.10),

    SS_AWARENESS(StatAttributes.AWARENESS.getName(), 0.67, .04, 0.11),
    SS_STRENGTH(StatAttributes.STRENGTH.getName(), 0.657, .035, 0.10),
    SS_SPEED(StatAttributes.SPEED.getName(), .803, .03, 0.07),
    SS_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.50, .03, 0.10),
    SS_TACKLE(StatAttributes.TACKLE.getName(), 0.657, .03, 0.07),
    SS_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), 0.35, .03, 0.07),
    SS_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), 0.36, .03, 0.08),
    SS_CATCHING(StatAttributes.CATCHING.getName(), 0.607, .03, 0.10),
    SS_CARRYING(StatAttributes.CARRYING.getName(), 0.584, .03, 0.10),
    SS_ACCELERATION(StatAttributes.ACCELERATION.getName(), .817, .0175, 0.03),
    SS_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.47, .03, 0.12),
    SS_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), 0.53, .03, 0.13),
    SS_AGILITY(StatAttributes.AGILITY.getName(), .78, .03, 0.07),
    SS_INJURY(StatAttributes.INJURY.getName(), .78, .03, 0.07),
    SS_STAMINA(StatAttributes.STAMINA.getName(), .82, .03, 0.07),
    SS_THROW_POWER(StatAttributes.THROW_POWER.getName(), 0.37, .03, 0.06),
    SS_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), 0.712, .03, 0.07),
    SS_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), 0.99, .03, 0.15),
    SS_KICK_POWER(StatAttributes.KICK_POWER.getName(), 0.29, .03, 0.04),
    SS_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), 0.25, .03, 0.04),
    SS_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), 0.14, .03, 0.02),
    SS_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), 0.27, .03, 0.04),

    C_AWARENESS(StatAttributes.AWARENESS.getName(), 0.761, .0175, 0.07),
    C_STRENGTH(StatAttributes.STRENGTH.getName(), 0.77, .03, 0.07),
    C_SPEED(StatAttributes.SPEED.getName(), 0.55, .03, 0.10),
    C_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.26, .03, 0.12),
    C_TACKLE(StatAttributes.TACKLE.getName(), 0.25, .03, 0.12),
    C_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), .7, .025, 0.07),
    C_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), .7, .025, 0.07),
    C_CATCHING(StatAttributes.CATCHING.getName(), 0.34, .03, 0.05),
    C_CARRYING(StatAttributes.CARRYING.getName(), 0.53, .03, 0.08),
    C_ACCELERATION(StatAttributes.ACCELERATION.getName(), .6738, .03, 0.07),
    C_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.21, .03, 0.10),
    C_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), 0.19, .03, 0.10),
    C_AGILITY(StatAttributes.AGILITY.getName(), 0.5513, .03, 0.07),
    C_INJURY(StatAttributes.INJURY.getName(), .77, .03, 0.10),
    C_STAMINA(StatAttributes.STAMINA.getName(), .80, .03, 0.10),
    C_THROW_POWER(StatAttributes.THROW_POWER.getName(), 0.33, .03, 0.05),
    C_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), 0.19, .03, 0.03),
    C_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), 0.2, .03, 0.03),
    C_KICK_POWER(StatAttributes.KICK_POWER.getName(), 0.27, .03, 0.04),
    C_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), 0.26, .03, 0.04),
    C_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), 0.1, .03, 0.01),
    C_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), 0.14, .03, 0.02),

    G_AWARENESS(StatAttributes.AWARENESS.getName(), 0.7613, .02, 0.07),
    G_STRENGTH(StatAttributes.STRENGTH.getName(), 0.7434, .03, 0.07),
    G_SPEED(StatAttributes.SPEED.getName(), 0.556, .03, 0.10),
    G_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.29, .03, 0.04),
    G_TACKLE(StatAttributes.TACKLE.getName(), 0.30, .03, 0.08),
    G_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), .6738, .03, 0.07),
    G_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), .7044, .03, 0.07),
    G_CATCHING(StatAttributes.CATCHING.getName(), 0.34, .03, 0.05),
    G_CARRYING(StatAttributes.CARRYING.getName(), 0.53, .03, 0.08),
    G_ACCELERATION(StatAttributes.ACCELERATION.getName(), .709, .03, 0.07),
    G_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.23, .03, 0.03),
    G_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), 0.19, .03, 0.03),
    G_AGILITY(StatAttributes.AGILITY.getName(), 0.595, .03, 0.10),
    G_INJURY(StatAttributes.INJURY.getName(), .78, .03, 0.10),
    G_STAMINA(StatAttributes.STAMINA.getName(), .80, .03, 0.10),
    G_THROW_POWER(StatAttributes.THROW_POWER.getName(), 0.34, .03, 0.05),
    G_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), 0.19, .03, 0.03),
    G_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), 0.2, .03, 0.03),
    G_KICK_POWER(StatAttributes.KICK_POWER.getName(), 0.29, .03, 0.04),
    G_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), 0.29, .03, 0.04),
    G_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), 0.1, .03, 0.01),
    G_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), 0.16, .03, 0.02),

    DT_AWARENESS(StatAttributes.AWARENESS.getName(), 0.72, .035, 0.07),
    DT_STRENGTH(StatAttributes.STRENGTH.getName(), .814, .03, 0.06),
    DT_SPEED(StatAttributes.SPEED.getName(), 0.6753, .03, 0.07),
    DT_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.7308, .03, 0.08),
    DT_TACKLE(StatAttributes.TACKLE.getName(), .7585, .03, 0.05),
    DT_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), 0.49, .03, 0.11),
    DT_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), 0.48, .03, 0.11),
    DT_CATCHING(StatAttributes.CATCHING.getName(), 0.31, .03, 0.05),
    DT_CARRYING(StatAttributes.CARRYING.getName(), 0.5, .03, 0.07),
    DT_ACCELERATION(StatAttributes.ACCELERATION.getName(), .7308, .03, 0.06),
    DT_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.31, .03, 0.05),
    DT_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), 0.26, .03, 0.04),
    DT_AGILITY(StatAttributes.AGILITY.getName(), 0.6475, .03, 0.08),
    DT_INJURY(StatAttributes.INJURY.getName(), .77, .03, 0.12),
    DT_STAMINA(StatAttributes.STAMINA.getName(), .7447, .03, 0.12),
    DT_THROW_POWER(StatAttributes.THROW_POWER.getName(), 0.31, .03, 0.05),
    DT_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), 0.3, .03, 0.04),
    DT_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), 0.41, .03, 0.06),
    DT_KICK_POWER(StatAttributes.KICK_POWER.getName(), 0.26, .03, 0.04),
    DT_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), 0.23, .03, 0.03),
    DT_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), 0.09, .03, 0.01),
    DT_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), 0.15, .03, 0.02),

    K_AWARENESS(StatAttributes.AWARENESS.getName(), 0.65, .03, 0.07),
    K_STRENGTH(StatAttributes.STRENGTH.getName(), 0.50, .04, 0.12),
    K_SPEED(StatAttributes.SPEED.getName(), 0.658, .035, 0.10),
    K_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.45, .03, 0.14),
    K_TACKLE(StatAttributes.TACKLE.getName(), 0.60, .035, 0.14),
    K_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), 0.21, .03, 0.03),
    K_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), 0.21, .03, 0.03),
    K_CATCHING(StatAttributes.CATCHING.getName(), 0.26, .03, 0.04),
    K_CARRYING(StatAttributes.CARRYING.getName(), 0.5, .03, 0.07),
    K_ACCELERATION(StatAttributes.ACCELERATION.getName(), 0.712, .03, 0.10),
    K_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.17, .03, 0.03),
    K_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), 0.23, .03, 0.03),
    K_AGILITY(StatAttributes.AGILITY.getName(), 0.590, .03, 0.10),
    K_INJURY(StatAttributes.INJURY.getName(), .80, .03, 0.10),
    K_STAMINA(StatAttributes.STAMINA.getName(), .80, .03, 0.10),
    K_THROW_POWER(StatAttributes.THROW_POWER.getName(), 0.41, .03, 0.06),
    K_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), 0.17, .03, 0.03),
    K_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), 0.21, .03, 0.03),
    K_KICK_POWER(StatAttributes.KICK_POWER.getName(), .907, .02, .06),
    K_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), .848, .025, .07),
    K_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), 0.29, .03, 0.04),
    K_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), 0.15, .03, 0.02),

    P_AWARENESS(StatAttributes.AWARENESS.getName(), 0.634, .03, 0.07),
    P_STRENGTH(StatAttributes.STRENGTH.getName(), 0.458, .03, 0.07),
    P_SPEED(StatAttributes.SPEED.getName(), 0.698, .0275, 0.07),
    P_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.50, .035, 0.14),
    P_TACKLE(StatAttributes.TACKLE.getName(), 0.60, .03, 0.07),
    P_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), 0.22, .03, 0.03),
    P_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), 0.21, .03, 0.03),
    P_CATCHING(StatAttributes.CATCHING.getName(), 0.27, .03, 0.04),
    P_CARRYING(StatAttributes.CARRYING.getName(), 0.54, .03, 0.08),
    P_ACCELERATION(StatAttributes.ACCELERATION.getName(), 0.722, .03, 0.07),
    P_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.21, .03, 0.03),
    P_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), 0.26, .03, 0.04),
    P_AGILITY(StatAttributes.AGILITY.getName(), 0.67, .03, 0.10),
    P_INJURY(StatAttributes.INJURY.getName(), .77, .03, 0.10),
    P_STAMINA(StatAttributes.STAMINA.getName(), .80, .03, 0.10),
    P_THROW_POWER(StatAttributes.THROW_POWER.getName(), 0.41, .03, 0.06),
    P_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), 0.17, .03, 0.03),
    P_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), 0.27, .03, 0.04),
    P_KICK_POWER(StatAttributes.KICK_POWER.getName(), .907, .02, .06),
    P_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), .839, .03, .07),
    P_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), 0.31, .03, 0.05),
    P_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), 0.17, .03, 0.03),

    FB_AWARENESS(StatAttributes.AWARENESS.getName(), 0.60, .03, 0.10),
    FB_STRENGTH(StatAttributes.STRENGTH.getName(), 0.70, .03, 0.07),
    FB_SPEED(StatAttributes.SPEED.getName(), .575, .03, 0.07),
    FB_BREAK_BLOCK(StatAttributes.BREAK_BLOCK.getName(), 0.43, .03, 0.12),
    FB_TACKLE(StatAttributes.TACKLE.getName(), 0.45, .03, 0.12),
    FB_RUN_BLOCKING(StatAttributes.RUN_BLOCKING.getName(), 0.575, .03, 0.07),
    FB_PASS_BLOCKING(StatAttributes.PASS_BLOCKING.getName(), 0.52, .03, 0.07),
    FB_CATCHING(StatAttributes.CATCHING.getName(), 0.557, .03, 0.10),
    FB_CARRYING(StatAttributes.CARRYING.getName(), .675, .03, 0.07),
    FB_ACCELERATION(StatAttributes.ACCELERATION.getName(), .625, .03, 0.07),
    FB_BREAK_TACKLE(StatAttributes.BREAK_TACKLE.getName(), 0.65, .03, 0.07),
    FB_ELUSIVENESS(StatAttributes.ELUSIVENESS.getName(), 0.375, .03, 0.12),
    FB_AGILITY(StatAttributes.AGILITY.getName(), .55, .03, 0.05),
    FB_INJURY(StatAttributes.INJURY.getName(), .77, .03, 0.07),
    FB_STAMINA(StatAttributes.STAMINA.getName(), .80, .03, 0.07),
    FB_THROW_POWER(StatAttributes.THROW_POWER.getName(), 0.46, .03, 0.07),
    FB_MAN_COVERAGE(StatAttributes.MAN_COVERAGE.getName(), 0.3, .03, 0.04),
    FB_ZONE_COVERAGE(StatAttributes.ZONE_COVERAGE.getName(), 0.39, .03, 0.06),
    FB_KICK_POWER(StatAttributes.KICK_POWER.getName(), 0.3, .03, 0.04),
    FB_KICK_ACCURACY(StatAttributes.KICK_ACCURACY.getName(), 0.28, .03, 0.04),
    FB_THROW_ACCURACY(StatAttributes.THROW_ACCURACY.getName(), 0.21, .03, 0.03),
    FB_ROUTE_RUNNING(StatAttributes.ROUTE_RUNNING.getName(), 0.50, .03, 0.10);

    public final static List <BaseAttributes> QB_ATTRIBUTES = Arrays.asList(
            QB_AWARENESS,
            QB_STRENGTH,
            QB_SPEED,
            QB_BREAK_BLOCK,
            QB_TACKLE,
            QB_RUN_BLOCKING,
            QB_PASS_BLOCKING,
            QB_CATCHING,
            QB_CARRYING,
            QB_ACCELERATION,
            QB_BREAK_TACKLE,
            QB_ELUSIVENESS,
            QB_AGILITY,
            QB_INJURY,
            QB_STAMINA,
            QB_THROW_POWER,
            QB_MAN_COVERAGE,
            QB_ZONE_COVERAGE,
            QB_KICK_POWER,
            QB_KICK_ACCURACY,
            QB_THROW_ACCURACY,
            QB_ROUTE_RUNNING
    );

    public final static List <BaseAttributes> TE_ATTRIBUTES = Arrays.asList(
            TE_AWARENESS,
            TE_STRENGTH,
            TE_SPEED,
            TE_BREAK_BLOCK,
            TE_TACKLE,
            TE_RUN_BLOCKING,
            TE_PASS_BLOCKING,
            TE_CATCHING,
            TE_CARRYING,
            TE_ACCELERATION,
            TE_BREAK_TACKLE,
            TE_ELUSIVENESS,
            TE_AGILITY,
            TE_INJURY,
            TE_STAMINA,
            TE_THROW_POWER,
            TE_MAN_COVERAGE,
            TE_ZONE_COVERAGE,
            TE_KICK_POWER,
            TE_KICK_ACCURACY,
            TE_THROW_ACCURACY,
            TE_ROUTE_RUNNING
    );

    public final static List <BaseAttributes> WR_ATTRIBUTES = Arrays.asList(
            WR_AWARENESS,
            WR_STRENGTH,
            WR_SPEED,
            WR_BREAK_BLOCK,
            WR_TACKLE,
            WR_RUN_BLOCKING,
            WR_PASS_BLOCKING,
            WR_CATCHING,
            WR_CARRYING,
            WR_ACCELERATION,
            WR_BREAK_TACKLE,
            WR_ELUSIVENESS,
            WR_AGILITY,
            WR_INJURY,
            WR_STAMINA,
            WR_THROW_POWER,
            WR_MAN_COVERAGE,
            WR_ZONE_COVERAGE,
            WR_KICK_POWER,
            WR_KICK_ACCURACY,
            WR_THROW_ACCURACY,
            WR_ROUTE_RUNNING
    );

    public final static List <BaseAttributes> OLB_ATTRIBUTES = Arrays.asList(
            OLB_AWARENESS,
            OLB_STRENGTH,
            OLB_SPEED,
            OLB_BREAK_BLOCK,
            OLB_TACKLE,
            OLB_RUN_BLOCKING,
            OLB_PASS_BLOCKING,
            OLB_CATCHING,
            OLB_CARRYING,
            OLB_ACCELERATION,
            OLB_BREAK_TACKLE,
            OLB_ELUSIVENESS,
            OLB_AGILITY,
            OLB_INJURY,
            OLB_STAMINA,
            OLB_THROW_POWER,
            OLB_MAN_COVERAGE,
            OLB_ZONE_COVERAGE,
            OLB_KICK_POWER,
            OLB_KICK_ACCURACY,
            OLB_THROW_ACCURACY,
            OLB_ROUTE_RUNNING
    );

    public final static List <BaseAttributes> MLB_ATTRIBUTES = Arrays.asList(
            MLB_AWARENESS,
            MLB_STRENGTH,
            MLB_SPEED,
            MLB_BREAK_BLOCK,
            MLB_TACKLE,
            MLB_RUN_BLOCKING,
            MLB_PASS_BLOCKING,
            MLB_CATCHING,
            MLB_CARRYING,
            MLB_ACCELERATION,
            MLB_BREAK_TACKLE,
            MLB_ELUSIVENESS,
            MLB_AGILITY,
            MLB_INJURY,
            MLB_STAMINA,
            MLB_THROW_POWER,
            MLB_MAN_COVERAGE,
            MLB_ZONE_COVERAGE,
            MLB_KICK_POWER,
            MLB_KICK_ACCURACY,
            MLB_THROW_ACCURACY,
            MLB_ROUTE_RUNNING
    );

    public final static List <BaseAttributes> DE_ATTRIBUTES = Arrays.asList(
            DE_AWARENESS,
            DE_STRENGTH,
            DE_SPEED,
            DE_BREAK_BLOCK,
            DE_TACKLE,
            DE_RUN_BLOCKING,
            DE_PASS_BLOCKING,
            DE_CATCHING,
            DE_CARRYING,
            DE_ACCELERATION,
            DE_BREAK_TACKLE,
            DE_ELUSIVENESS,
            DE_AGILITY,
            DE_INJURY,
            DE_STAMINA,
            DE_THROW_POWER,
            DE_MAN_COVERAGE,
            DE_ZONE_COVERAGE,
            DE_KICK_POWER,
            DE_KICK_ACCURACY,
            DE_THROW_ACCURACY,
            DE_ROUTE_RUNNING
    );

    public final static List <BaseAttributes> CB_ATTRIBUTES = Arrays.asList(
            CB_AWARENESS,
            CB_STRENGTH,
            CB_SPEED,
            CB_BREAK_BLOCK,
            CB_TACKLE,
            CB_RUN_BLOCKING,
            CB_PASS_BLOCKING,
            CB_CATCHING,
            CB_CARRYING,
            CB_ACCELERATION,
            CB_BREAK_TACKLE,
            CB_ELUSIVENESS,
            CB_AGILITY,
            CB_INJURY,
            CB_STAMINA,
            CB_THROW_POWER,
            CB_MAN_COVERAGE,
            CB_ZONE_COVERAGE,
            CB_KICK_POWER,
            CB_KICK_ACCURACY,
            CB_THROW_ACCURACY,
            CB_ROUTE_RUNNING
    );

    public final static List <BaseAttributes> OT_ATTRIBUTES = Arrays.asList(
            OT_AWARENESS,
            OT_STRENGTH,
            OT_SPEED,
            OT_BREAK_BLOCK,
            OT_TACKLE,
            OT_RUN_BLOCKING,
            OT_PASS_BLOCKING,
            OT_CATCHING,
            OT_CARRYING,
            OT_ACCELERATION,
            OT_BREAK_TACKLE,
            OT_ELUSIVENESS,
            OT_AGILITY,
            OT_INJURY,
            OT_STAMINA,
            OT_THROW_POWER,
            OT_MAN_COVERAGE,
            OT_ZONE_COVERAGE,
            OT_KICK_POWER,
            OT_KICK_ACCURACY,
            OT_THROW_ACCURACY,
            OT_ROUTE_RUNNING
    );

    public final static List <BaseAttributes> FS_ATTRIBUTES = Arrays.asList(
            FS_AWARENESS,
            FS_STRENGTH,
            FS_SPEED,
            FS_BREAK_BLOCK,
            FS_TACKLE,
            FS_RUN_BLOCKING,
            FS_PASS_BLOCKING,
            FS_CATCHING,
            FS_CARRYING,
            FS_ACCELERATION,
            FS_BREAK_TACKLE,
            FS_ELUSIVENESS,
            FS_AGILITY,
            FS_INJURY,
            FS_STAMINA,
            FS_THROW_POWER,
            FS_MAN_COVERAGE,
            FS_ZONE_COVERAGE,
            FS_KICK_POWER,
            FS_KICK_ACCURACY,
            FS_THROW_ACCURACY,
            FS_ROUTE_RUNNING
    );

    public final static List <BaseAttributes> HB_ATTRIBUTES = Arrays.asList(
            HB_AWARENESS,
            HB_STRENGTH,
            HB_SPEED,
            HB_BREAK_BLOCK,
            HB_TACKLE,
            HB_RUN_BLOCKING,
            HB_PASS_BLOCKING,
            HB_CATCHING,
            HB_CARRYING,
            HB_ACCELERATION,
            HB_BREAK_TACKLE,
            HB_ELUSIVENESS,
            HB_AGILITY,
            HB_INJURY,
            HB_STAMINA,
            HB_THROW_POWER,
            HB_MAN_COVERAGE,
            HB_ZONE_COVERAGE,
            HB_KICK_POWER,
            HB_KICK_ACCURACY,
            HB_THROW_ACCURACY,
            HB_ROUTE_RUNNING
    );

    public final static List <BaseAttributes> SS_ATTRIBUTES = Arrays.asList(
            SS_AWARENESS,
            SS_STRENGTH,
            SS_SPEED,
            SS_BREAK_BLOCK,
            SS_TACKLE,
            SS_RUN_BLOCKING,
            SS_PASS_BLOCKING,
            SS_CATCHING,
            SS_CARRYING,
            SS_ACCELERATION,
            SS_BREAK_TACKLE,
            SS_ELUSIVENESS,
            SS_AGILITY,
            SS_INJURY,
            SS_STAMINA,
            SS_THROW_POWER,
            SS_MAN_COVERAGE,
            SS_ZONE_COVERAGE,
            SS_KICK_POWER,
            SS_KICK_ACCURACY,
            SS_THROW_ACCURACY,
            SS_ROUTE_RUNNING
    );

    public final static List <BaseAttributes> C_ATTRIBUTES = Arrays.asList(
            C_AWARENESS,
            C_STRENGTH,
            C_SPEED,
            C_BREAK_BLOCK,
            C_TACKLE,
            C_RUN_BLOCKING,
            C_PASS_BLOCKING,
            C_CATCHING,
            C_CARRYING,
            C_ACCELERATION,
            C_BREAK_TACKLE,
            C_ELUSIVENESS,
            C_AGILITY,
            C_INJURY,
            C_STAMINA,
            C_THROW_POWER,
            C_MAN_COVERAGE,
            C_ZONE_COVERAGE,
            C_KICK_POWER,
            C_KICK_ACCURACY,
            C_THROW_ACCURACY,
            C_ROUTE_RUNNING
    );

    public final static List <BaseAttributes> G_ATTRIBUTES = Arrays.asList(
            G_AWARENESS,
            G_STRENGTH,
            G_SPEED,
            G_BREAK_BLOCK,
            G_TACKLE,
            G_RUN_BLOCKING,
            G_PASS_BLOCKING,
            G_CATCHING,
            G_CARRYING,
            G_ACCELERATION,
            G_BREAK_TACKLE,
            G_ELUSIVENESS,
            G_AGILITY,
            G_INJURY,
            G_STAMINA,
            G_THROW_POWER,
            G_MAN_COVERAGE,
            G_ZONE_COVERAGE,
            G_KICK_POWER,
            G_KICK_ACCURACY,
            G_THROW_ACCURACY,
            G_ROUTE_RUNNING
    );

    public final static List <BaseAttributes> DT_ATTRIBUTES = Arrays.asList(
            DT_AWARENESS,
            DT_STRENGTH,
            DT_SPEED,
            DT_BREAK_BLOCK,
            DT_TACKLE,
            DT_RUN_BLOCKING,
            DT_PASS_BLOCKING,
            DT_CATCHING,
            DT_CARRYING,
            DT_ACCELERATION,
            DT_BREAK_TACKLE,
            DT_ELUSIVENESS,
            DT_AGILITY,
            DT_INJURY,
            DT_STAMINA,
            DT_THROW_POWER,
            DT_MAN_COVERAGE,
            DT_ZONE_COVERAGE,
            DT_KICK_POWER,
            DT_KICK_ACCURACY,
            DT_THROW_ACCURACY,
            DT_ROUTE_RUNNING
    );

    public final static List <BaseAttributes> K_ATTRIBUTES = Arrays.asList(
            K_AWARENESS,
            K_STRENGTH,
            K_SPEED,
            K_BREAK_BLOCK,
            K_TACKLE,
            K_RUN_BLOCKING,
            K_PASS_BLOCKING,
            K_CATCHING,
            K_CARRYING,
            K_ACCELERATION,
            K_BREAK_TACKLE,
            K_ELUSIVENESS,
            K_AGILITY,
            K_INJURY,
            K_STAMINA,
            K_THROW_POWER,
            K_MAN_COVERAGE,
            K_ZONE_COVERAGE,
            K_KICK_POWER,
            K_KICK_ACCURACY,
            K_THROW_ACCURACY,
            K_ROUTE_RUNNING
    );

    public final static List <BaseAttributes> P_ATTRIBUTES = Arrays.asList(
            P_AWARENESS,
            P_STRENGTH,
            P_SPEED,
            P_BREAK_BLOCK,
            P_TACKLE,
            P_RUN_BLOCKING,
            P_CATCHING,
            P_CARRYING,
            P_ACCELERATION,
            P_BREAK_TACKLE,
            P_ELUSIVENESS,
            P_AGILITY,
            P_INJURY,
            P_STAMINA,
            P_PASS_BLOCKING,
            P_THROW_POWER,
            P_MAN_COVERAGE,
            P_ZONE_COVERAGE,
            P_KICK_POWER,
            P_KICK_ACCURACY,
            P_THROW_ACCURACY,
            P_ROUTE_RUNNING
    );

    public final static List <BaseAttributes> FB_ATTRIBUTES = Arrays.asList(
            FB_AWARENESS,
            FB_STRENGTH,
            FB_SPEED,
            FB_BREAK_BLOCK,
            FB_TACKLE,
            FB_RUN_BLOCKING,
            FB_PASS_BLOCKING,
            FB_CATCHING,
            FB_CARRYING,
            FB_ACCELERATION,
            FB_BREAK_TACKLE,
            FB_ELUSIVENESS,
            FB_AGILITY,
            FB_INJURY,
            FB_STAMINA,
            FB_THROW_POWER,
            FB_MAN_COVERAGE,
            FB_ZONE_COVERAGE,
            FB_KICK_POWER,
            FB_KICK_ACCURACY,
            FB_THROW_ACCURACY,
            FB_ROUTE_RUNNING
    );

    private final String name;
    private final double mean;
    private final double deviation;
    private final double cap;

    BaseAttributes(final String n, final double m, final double d, final double c){
        name = n;
        mean = m;
        deviation = d;
        cap = c;
    }

    public final String getName(){
        return name;
    }

    public final double getMean(){
        return mean;
    }

    public final double getDeviation(){
        return deviation;
    }

    public final double getCap(){
        return cap;
    }

}